### ISSUE TITLE
Prepare for v0.2.3

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#113]
**RELEASE:**
libseccomp: v0.2.3
libseccomp-sys: v0.2.1

**TODO:**
- [x] Solve all PRs and issues in https://github.com/libseccomp-rs/libseccomp-rs/milestone/2
- [x] Validate the crate documentation
  - [x] Run `cargo doc --no-deps`
- [x] Change `Cargo.toml`/`README.md`/`CHANGELOG.md` for v.0.2.3
- [x] Create v0.2.3 tag
- [x] Publish the libseccomp crate on crates.io
- [x] Create the release page in GitHub

**Comment by ManaSugi** [comment]
all works done
