### ISSUE TITLE
Upcomming libseccomp changes

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#142]
- [ ] New architectures: `sheb` and `sh` (relevant for `ScmpArch` and #125).
- [ ] New function: `seccomp_export_bpf_mem` (#121)
- [ ] Updated syscalls (relevant for #125).
- [ ] New errno: `-ERANGE`, returned by `seccomp_export_bpf_mem` (relevant for `SeccompErrno`)
- [ ] `seccomp_notify_fd` can return `-1` and `-EINVAL` (manpage only change?)

**Comment by ManaSugi** [comment]
Great. Thank you for creating this issue.

**Comment by ManaSugi** [comment]
Regarding new architecture:

`sheb` and `sh` hasn't been supported in Rust yet, so we don't need to support it. (LLVM hasn't support the architecture.)  
https://llvm.org/docs/CompilerWriterInfo.html#hardware


But, `loongarch64` and `m68k` should be supported because these are available in Rust.  
https://doc.rust-lang.org/rustc/platform-support/loongarch-linux.html
https://doc.rust-lang.org/rustc/platform-support/m68k-unknown-linux-gnu.html

**Comment by rusty-snake** [comment]
They may still be interesting because of `seccomp_export_bpf`.

**Comment by ManaSugi** [comment]
@rusty-snake 
> seccomp_notify_fd can return -1 and -EINVAL (manpage only change?)

Have this been solved since we supported [`ErrorKind::SysRawRc`](https://github.com/libseccomp-rs/libseccomp-rs/pull/227)?

**Comment by rusty-snake** [comment]
Not resolved by `SysRawRc` but nothing to act on anyway.

**Comment by ManaSugi** [comment]
@mayamrinal 

Do you have an interest about supportin `seccomp_transaction_start`, `seccomp_transaction_commit` and `seccomp_transaction_reject`?

**Comment by ManaSugi** [comment]
> [@mayamrinal](https://github.com/mayamrinal)
> 
> Do you have an interest about supporting `seccomp_transaction_start`, `seccomp_transaction_commit` and `seccomp_transaction_reject`?

I created the PR: https://github.com/libseccomp-rs/libseccomp-rs/pull/278

**Comment by ManaSugi** [comment]
We will support libseccomp v2.6.0 from the nexe release, so the next version 0.4.0 will be good i think.
