### ISSUE TITLE
Prepare for v0.3.0

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#168]
**RELEASE:**
libseccomp: v0.3.0

**TODO:**
- [x] Solve all PRs and issues in https://github.com/libseccomp-rs/libseccomp-rs/milestone/3
- [x] Validate the crate documentation
  - [x] Run `cargo doc --no-deps`
- [x] Change `Cargo.toml`, `README.md`, and `CHANGELOG.md` for v.0.3.0
- [x] Create v0.3.0 tag
- [x] Publish the libseccomp crate on crates.io
- [x] Create the release page in GitHub

**Comment by ManaSugi** [comment]
I released v0.3.0.
Thank you for your contributions @rusty-snake @savithry-j @boustrophedon!
