### ISSUE TITLE
[Release] Prepare for v0.4.0

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#261]
**RELEASE:**
libseccomp: v0.4.0
libseccomp-sys: v0.3.0

**TODO:**
- [x] Solve all PRs and issues in https://github.com/libseccomp-rs/libseccomp-rs/milestone/4
- [x] Format examples with `cargo +nightly fmt --all -- --config format_code_in_doc_comments=true`
- [x] Validate the crate documentation
  - [x] Run `make doc` and verify the documents on your local environment
- [x] Change `Cargo.toml`, `README.md`, and `CHANGELOG.md` for v.0.4.0
- [x] Create v0.4.0 tag for libseccomp
- [x] Publish the libseccomp and libseccomp-sys crate on crates.io
- [x] Create the release page in GitHub

**Comment by rusty-snake** [comment]
- [ ] Format examples with `cargo +nightly fmt --all -- --config format_code_in_doc_comments=true`

**Comment by rusty-snake** [comment]
@ManaSugi can we get libseccomp v2.5.5 support out.

#263 is the last open item in https://github.com/libseccomp-rs/libseccomp-rs/milestone/4.

**Comment by rusty-snake** [comment]
https://github.com/seccomp/libseccomp/releases/tag/v2.6.0

**Comment by sophie-h** [comment]
Thanks for creating this crate. Is there a chance for a new release? Otherwise, it might be good to look for a new maintainer?

**Comment by rusty-snake** [comment]
I could tag a release here on GitHub. However I can not publish it to crates.io. Only @ManaSugi can.
IMHO not worth the effort.
(I'm in the process of migrate my own projects away from libseccomp, so no personal interest too.)

> Otherwise, it might be good to look for a new maintainer?

See also https://github.com/seccomp/libseccomp/pull/411 / https://github.com/seccomp/libseccomp/issues/323

---

ping @chethanah, @savithry-j, @mayamrinal is case you know something or can add new information.

**Comment by ManaSugi** [comment]
@rusty-snake @sophie-h I approgize for the late reply. I came back to this libseccomp-rs. I'll do release work for v2.6 this week.

**Comment by sophie-h** [comment]
wow, thanks. that's great news!

**Comment by ManaSugi** [comment]
@sophie-h 
Currently i have been working on passing the CI failure
Ref. https://github.com/libseccomp-rs/libseccomp-rs/pull/273

If this pr is merged, we can release the new version of libseccomp-rs. T

**Comment by ManaSugi** [comment]
This will be 0.4.0, not 0.3.1

**Comment by ManaSugi** [comment]
@sophie-h 
we have released libseccomp v0.4.0 and libseccomp-sys v0.3.0

libseccomp v0.4.0: https://crates.io/crates/libseccomp/0.4.0
libseccomp-sys v0.3.0: https://crates.io/crates/libseccomp-sys/0.3.0
