### ISSUE TITLE
Prepare for v0.2.0 

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#53]
v0.2.0 milestone: https://github.com/libseccomp-rs/libseccomp-rs/milestone/1

**Release:**
`libseccomp`: v0.2.0
`libseccomp-sys`: v0.2.0

**TODO:**
- [x] Merge all PRs in the milestone into `main` branch
- [x] Update `CHANGELOG.md`
   * Add all changes from v0.1.3
   * The interfaces will be changed dramatically from v0.2.0, so we MUST write the annotations of the change.
- [x] Validate the crate documentation
- [x] Change `cargo.toml`/`README.md` of `libseccomp`/`libseccomp-sys` for v0.2.0 
- [x] Create v0.2.0 tag
- [x] Publish the crates on [crates.io](https://crates.io/) 
   * Run `cargo doc --no-deps`
   * At first, I need to pubslih the `libseccomp-sys` crate. Second, I'll publish the `libseccomp` crate.
- [x] Create the release page in Github

**Comment by rusty-snake** [comment]
<details><summary>wip changelog</summary>

```diff
diff --git a/CHANGELOG.md b/CHANGELOG.md
index d779c24..93305e9 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -7,16 +7,31 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 
 ## Unreleased
 ### Added
-- `ScmpArgCompare::new` is now a `const fn`.
+- `ScmpVersion::current()` as rustifyed replacement for `get_library_version()`.
+- `ScmpFilterContext::get_no_new_privs_bit()` to query the state of the nnp bit.
+- `ScmpArch::native()` as rustifyed replacement for `get_native_arch()`.
+- `ScmpFilterContext::as_ptr()`
+- `scmp_cmp!`
 
 ### Changed
+- `ScmpArgCompare::new` is now a `const fn`.
 - `ScmpAction::Errno` now holds an `i32` to make `ScmpAction::Errno(libc::EPERM)`
   work without casting.
 - `ScmpAction::Trace` now holds an `u16` since you can not use any more bits anyway.
+- `set_filter_attr` takes `&mut self` rather than `&self`.
+- `export_{pfc,bpf}` take a `&mut` reference instead of consuming ownership.
+- `export_{pfc,bpf}` take all types which implement `AsRawFd`.
+- masked equal
+
+### Deprecated
+- `get_library_version()` use `ScmpVersion::current()` instead.
+- `get_native_arch()` use `ScmpArch::native()` instead.
 
 ### Removed
 - `Clone` on `ScmpFilterContext` because it cauesed double-free/use-after-free
    in safe code.
+- `ScmpData` (was unused)
+- `.to_native()` functions
 
 ### Security
 - Fixed double-free/use-after-free when cloning `ScmpFilterContext`.
```

</details>

**Comment by rusty-snake** [comment]
When #45 and #41 (work is done, just waiting on #47) are merged/closed, I think we have all API breaking changes done and can focus on releasing 0.2.0.

**Comment by ManaSugi** [comment]
All works done. Thank you for your great contributions!! @rusty-snake

**Comment by ManaSugi** [comment]
I cannot see `notify` module in [docs](https://docs.rs/libseccomp/0.2.0/libseccomp/).
When I generated the docs using `cargo doc --no-deps` in local, I was able to see the `notify` doc. I'm not sure...

**Comment by rusty-snake** [comment]
```rust
#[cfg(libseccomp_v2_5)]
pub mod notify;
```

**Comment by ManaSugi** [comment]
Dose `cargo doc` ignore `cfg`?

**Comment by rusty-snake** [comment]
The docs.rs environment doesn't have libseccomp (>=2.5).

**Comment by rusty-snake** [comment]
Probably we need to `#[cfg(any(libseccomp_v2_5, docsrs))]` or similar.

https://docs.rs/about/builds

**Comment by ManaSugi** [comment]
Thank you for the information. I see.... should we fix it and release `v0.2.1` right now?

**Comment by rusty-snake** [comment]
I think a `0.2.1 - fix docs.rs build` release is fine.

**Comment by ManaSugi** [comment]
Sure, I'll create a PR. sorry for inconvenience.
