### ISSUE TITLE
Prepare for v0.2.1

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#76]
**Release:**
`libseccomp`: v0.2.1

**TODO:**
- [x] Merge #75 into `main` branch
- [x] Validate the crate documentation
- [x] Change `cargo.toml`/`README.md` of the `libseccomp` crate for v0.2.1
- [x] Create v0.2.1 tag
- [x] Publish the crates on [crates.io](https://crates.io/) 
   * Run `cargo doc --no-deps`
- [x] Create the release page in Github

**Comment by ManaSugi** [comment]
Hmm.. I cannot see the `notify` module yet.
